/** Chinese labels for tzdb `alternativeName` zone groups. */
export const ZONE_GROUP_ZH = {
  'Acre Time': '阿克里时间',
  'Alaska Time': '阿拉斯加时间',
  'Amazon Time': '亚马逊时间',
  'American Samoa Time': '美属萨摩亚时间',
  'Atlantic Time': '大西洋时间',
  'Australian Central Time': '澳大利亚中部时间',
  'Australian Central Western Time': '澳大利亚中西部时间',
  'Australian Eastern Time': '澳大利亚东部时间',
  'Australian Western Time': '澳大利亚西部时间',
  'Azores Time': '亚速尔时间',
  'Bougainville Time': '布干维尔时间',
  'Brasilia Time': '巴西利亚时间',
  'Central Africa Time': '中非时间',
  'Central European Time': '中欧时间',
  'Central Indonesia Time': '印尼中部时间',
  'Central Time': '中部时间',
  'Chatham Time': '查塔姆时间',
  'Chile Time': '智利时间',
  'Chuuk Time': '楚克时间',
  'Davis Time': '戴维斯时间',
  'Dumont d’Urville Time': '迪蒙迪维尔时间',
  'Easter Island Time': '复活节岛时间',
  'Eastern European Time': '东欧时间',
  'Eastern Indonesia Time': '印尼东部时间',
  'Eastern Time': '东部时间',
  'Ecuador Time': '厄瓜多尔时间',
  'Fernando de Noronha Time': '费尔南多迪诺罗尼亚时间',
  'Galapagos Time': '加拉帕戈斯时间',
  'Gambier Time': '甘比尔时间',
  'Gilbert Islands Time': '吉尔伯特群岛时间',
  'Greenland Time': '格陵兰时间',
  'Greenwich Mean Time': '格林尼治标准时间',
  'Hawaii-Aleutian Time': '夏威夷-阿留申时间',
  'Hovd Time': '科布多时间',
  'Irkutsk Time': '伊尔库茨克时间',
  'Kamchatka Time': '堪察加时间',
  'Kosrae Time': '科斯雷时间',
  'Line Islands Time': '莱恩群岛时间',
  'Lord Howe Time': '豪勋爵岛时间',
  'Marquesas Time': '马克萨斯时间',
  'Mawson Time': '莫森时间',
  'Mexican Pacific Time': '墨西哥太平洋时间',
  'Moscow Time': '莫斯科时间',
  'Mountain Time': '山地时间',
  'New Zealand Time': '新西兰时间',
  'Newfoundland Time': '纽芬兰时间',
  'Novosibirsk Time': '新西伯利亚时间',
  'Omsk Time': '鄂木斯克时间',
  'Pacific Time': '太平洋时间',
  'Papua New Guinea Time': '巴布亚新几内亚时间',
  'Phoenix Islands Time': '菲尼克斯群岛时间',
  'Sakhalin Time': '萨哈林时间',
  'Samara Time': '萨马拉时间',
  'Syowa Time': '昭和时间',
  'Tahiti Time': '塔希提时间',
  'Ulaanbaatar Time': '乌兰巴托时间',
  'Vladivostok Time': '符拉迪沃斯托克时间',
  'Wake Island Time': '威克岛时间',
  'West Africa Time': '西非时间',
  'Western European Time': '西欧时间',
  'Western Indonesia Time': '印尼西部时间',
  'Yakutsk Time': '雅库茨克时间',
  'Yekaterinburg Time': '叶卡捷琳堡时间',
  'Yukon Time': '育空时间',
  'China Time': '中国时间',
  'Japan Time': '日本时间',
  'Korean Time': '韩国时间',
  'India Time': '印度时间',
  'Singapore Time': '新加坡时间',
  'Hong Kong Time': '香港时间',
  'Gulf Time': '海湾时间',
  'Arabian Time': '阿拉伯时间',
  'Israel Time': '以色列时间',
  'Iran Time': '伊朗时间',
  'Turkey Time': '土耳其时间',
  'South Africa Time': '南非时间',
  'East Africa Time': '东非时间',
  'Nepal Time': '尼泊尔时间',
  'Pakistan Time': '巴基斯坦时间',
  'Bangladesh Time': '孟加拉时间',
  'Indochina Time': '印度支那时间',
  'Philippine Time': '菲律宾时间',
  'Malaysia Time': '马来西亚时间',
  'Myanmar Time': '缅甸时间',
  'Afghanistan Time': '阿富汗时间',
  'Fiji Time': '斐济时间',
  'Colombia Time': '哥伦比亚时间',
  'Peru Time': '秘鲁时间',
  'Venezuela Time': '委内瑞拉时间',
  'Argentina Time': '阿根廷时间',
  'Kazakhstan Time': '哈萨克斯坦时间',
  'Uzbekistan Time': '乌兹别克斯坦时间',
  'Coordinated Universal Time': '协调世界时',
}

/** Editorial overrides where Intl.DisplayNames wording is too formal/ambiguous. */
export const COUNTRY_ZH_OVERRIDE = {
  AE: '阿联酋',
  TW: '中国台湾',
  HK: '中国香港',
  MO: '中国澳门',
  US: '美国',
  GB: '英国',
  RU: '俄罗斯',
  KR: '韩国',
  KP: '朝鲜',
  LA: '老挝',
  VA: '梵蒂冈',
  CD: '刚果（金）',
  CG: '刚果（布）',
  CI: '科特迪瓦',
  SZ: '斯威士兰',
  MK: '北马其顿',
  TL: '东帝汶',
  BN: '文莱',
  MM: '缅甸',
  SY: '叙利亚',
  PS: '巴勒斯坦',
}
